### ISSUE TITLE
项目跑步起来，没有3000接口，建议数据可以放在easy-mock里面

### ISSUE THREAD

**Issue by super918180** [Harhao/miniProgram#1]

**Comment by Harhao** [comment]
3000端口是获取项目的本地地理位置和全国所有的城市信息，所以可以在[这个地址获取json数据](https://github.com/Harhao/crawEyeCatCities/blob/master/getCity/cities.json)；获取地址是[http://maoyan.com/ajax/cities](http://maoyan.com/ajax/cities)。你也可以在我新上传的代码中有api.zip包，可以启动node服务获取地理位置信息 @super918180
