### ISSUE TITLE
Taro.request 跨域问题，请问怎么解决

### ISSUE THREAD

**Issue by zengcongjun** [Harhao/miniProgram#2]
Failed to load https://m.maoyan.com/ajax/mostExpected?ci=&limit=10&offset=0&token=&: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by zengcongjun** [comment]
![image](https://user-images.githubusercontent.com/31197352/43710648-c9be7cca-99a2-11e8-83f2-93d6dfbaff7e.png)

**Comment by Harhao** [comment]
可以使用中间代理收发的方式来获取数据，但是在小程序开发中没有出现跨域的问题，你是把他编译成h5的形式？？

**Comment by chenjing1552** [comment]
请问你怎么解决的?
