### ISSUE TITLE
VM4185:1 thirdScriptError   sdk uncaught third Error   _index2.default.initPxTransform is not a function   TypeError: _index2.default.initPxTransform is not a function     at http://127.0.0.1:35580/appservice/app.js:92:17     at require (http://127.0.0.1:35580/appservice/__dev__/WAService.js:1:716549)     at <anonymous>:1:1     at HTMLScriptElement.scriptLoaded (http://127.0.0.1:35580/appservice/appservice?t=1543411911267:1639:23)

### ISSUE THREAD

**Issue by jackylee1** [Harhao/miniProgram#4]
VM4185:1 thirdScriptError 
 sdk uncaught third Error 
 _index2.default.initPxTransform is not a function 
 TypeError: _index2.default.initPxTransform is not a function
    at http://127.0.0.1:35580/appservice/app.js:92:17
    at require (http://127.0.0.1:35580/appservice/__dev__/WAService.js:1:716549)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:35580/appservice/appservice?t=1543411911267:1639:23)

这是怎么回事呢

**Comment by Harhao** [comment]
@jackylee1 可能要更新一下Taro的版本了，我开发的时候Taro正式版本1.0都还没有出来。可能有部分功能不支持了
